Update terraform
open-toolchain/tekton-catalog pull request #268
Opened 2021-06-03 16:40 UTC by jparra5

2021-06-03 19:08 UTC, jparra5 commented
@jauninb

2021-06-04 07:48 UTC, jauninb commented on cra/task-terraform-scan.yaml
> +      description: git commit id
Existing user/adopter of this task will be broken as this commit-id parameter is a new expected parameter for this task
So in order to be previous-versio compliant a default value should be defined (asusming "") and take in account by the underlying node program

2021-06-04 07:48 UTC, jauninb requested changes
commit-id new parameter is abreaking change - default value needed

2021-06-04 14:49 UTC, jparra5 commented
@jauninb @padraic-edwards The comment has been resolved.

2021-06-04 15:11 UTC, jauninb approved these changes
LGTM

2021-06-04 15:11 UTC, merged